name: diplomka
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  bloc_test: ^9.1.6
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.0
  insta_image_viewer: ^1.0.2
  sliding_clipped_nav_bar: ^3.1.0+4
  uuid: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  patrol: ^3.6.0

flutter:
  uses-material-design: true  
  assets:
    - assets/images/plzenka.jpeg
    - assets/images/plzenka_2.jpeg
    - assets/images/ajeto.jpeg
    - assets/images/ajeto2.jpeg
    - assets/images/dasen.jpeg
    - assets/images/famu.jpeg
    - assets/images/famu2.jpeg
    - assets/images/herba_cafe.jpeg
    - assets/images/herba_cafe2.jpeg
    - assets/images/nadrazka.jpeg
    - assets/images/nadrazka_2.jpeg
    - assets/images/oaza.jpeg
    - assets/images/oaza_2.jpeg
    - assets/images/oaza_3.jpeg
    - assets/images/oaza_4.jpeg
    - assets/images/u_sadu.jpeg
    - assets/images/u_sadu_2.jpeg
    - assets/images/u_sadu_3.jpeg
    - assets/images/u_sadu_4.jpeg
    - assets/images/u_sadu_5.jpeg
    - assets/images/u_sadu_6.jpeg
    - assets/images/v_siti.jpeg
    - assets/images/v_siti_2.jpeg
    - assets/images/v_siti_3.jpeg
    - assets/images/vecernice.jpeg
    - assets/images/vecernice_2.jpeg
    - assets/images/vecernice_3.jpeg
    - assets/images/vecernice_4.jpeg
    - assets/images/woodoo.jpeg
    - assets/images/woodoo_2.jpeg
    - assets/images/woodoo_3.jpeg
    - assets/images/woodoo_4.jpeg
    - assets/images/zazemi.jpeg
    - assets/images/zazemi_2.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf  
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Light.ttf
patrol:
  app_name: FootballApp
  android:
    package_name: com.example.diplomka
  ios:
    bundle_id: com.example.diplomka

